In [20]:
%matplotlib inline
from pathlib import Path
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import numpy as np

In [3]:
game_df = pd.read_csv("games.csv")
game_df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,20200,Galactic Bowling,"Oct 21, 2008",0 - 20000,0,0,19.99,0,Galactic Bowling is an exaggerated and stylize...,['English'],...,0,0,0,Perpetual FX Creative,Perpetual FX Creative,"Single-player,Multi-player,Steam Achievements,...","Casual,Indie,Sports","Indie,Casual,Sports,Bowling",https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...
1,655370,Train Bandit,"Oct 12, 2017",0 - 20000,0,0,0.99,0,THE LAW!! Looks to be a showdown atop a train....,"['English', 'French', 'Italian', 'German', 'Sp...",...,0,0,0,Rusty Moyher,Wild Rooster,"Single-player,Steam Achievements,Full controll...","Action,Indie","Indie,Action,Pixel Graphics,2D,Retro,Arcade,Sc...",https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...
2,1732930,Jolt Project,"Nov 17, 2021",0 - 20000,0,0,4.99,0,Jolt Project: The army now has a new robotics ...,"['English', 'Portuguese - Brazil']",...,0,0,0,Campião Games,Campião Games,Single-player,"Action,Adventure,Indie,Strategy",NaN,https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...
3,1355720,Henosis™,"Jul 23, 2020",0 - 20000,0,0,5.99,0,HENOSIS™ is a mysterious 2D Platform Puzzler w...,"['English', 'French', 'Italian', 'German', 'Sp...",...,0,0,0,Odd Critter Games,Odd Critter Games,"Single-player,Full controller support","Adventure,Casual,Indie","2D Platformer,Atmospheric,Surreal,Mystery,Puzz...",https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...
4,1139950,Two Weeks in Painland,"Feb 3, 2020",0 - 20000,0,0,0.00,0,ABOUT THE GAME Play as a hacker who has arrang...,"['English', 'Spanish - Spain']",...,0,0,0,Unusual Games,Unusual Games,"Single-player,Steam Achievements","Adventure,Indie","Indie,Adventure,Nudity,Violent,Sexual Content,...",https://cdn.akamai.steamstatic.com/steam/apps/...,http://cdn.akamai.steamstatic.com/steam/apps/2...

In [4]:
game_df.columns

Index(['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'DLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='object')

In [5]:
game_df.dtypes

AppID                           int64
Name                           object
Release date                   object
Estimated owners               object
Peak CCU                        int64
Required age                    int64
Price                         float64
DLC count                       int64
About the game                 object
Supported languages            object
Full audio languages           object
Reviews                        object
Header image                   object
Website                        object
Support url                    object
Support email                  object
Windows                          bool
Mac                              bool
Linux                            bool
Metacritic score                int64
Metacritic url                 object
User score                      int64
Positive                        int64
Negative                        int64
Score rank                    float64
Achievements                    int64
Recommendations                 int64
Notes                          object
Average playtime forever        int64
Average playtime two weeks      int64
Median playtime forever         int64
Median playtime two weeks       int64
Developers                     object
Publishers                     object
Categories                     object
Genres                         object
Tags                           object
Screenshots                    object
Movies                         object
dtype: object

In [6]:
tags_df = game_df[["Name","Tags","Positive"]]
tags_df.head()

,Name,Tags,Positive
0,Galactic Bowling,"Indie,Casual,Sports,Bowling",6
1,Train Bandit,"Indie,Action,Pixel Graphics,2D,Retro,Arcade,Sc...",53
2,Jolt Project,NaN,0
3,Henosis™,"2D Platformer,Atmospheric,Surreal,Mystery,Puzz...",3
4,Two Weeks in Painland,"Indie,Adventure,Nudity,Violent,Sexual Content,...",50

In [7]:
tags_df = game_df.groupby("Tags")["Positive"].mean()
tags_df.head()

Tags
1980s,Action,Retro,Pixel Graphics,Platformer,Side Scroller,2D Platformer,Action-Adventure,Trading Card Game,Trading,2D,Colorful,Funny,Old School,Time Travel,Combat,Controller,Singleplayer                        6.0
1980s,Cyberpunk,Retro,Text-Based,Crime,Trading,Replay Value,Dark Humor,Minimalist,Colorful,Management,Strategy,Dark Comedy,Casual,Capitalism,Dystopian,Stylized,Political,Dark,Conspiracy                          7.0
1980s,Electronic Music,Runner,Difficult,3D Platformer,Arcade,Physics,Atmospheric,Platformer,Precision Platformer,Colorful,Singleplayer,Action,Retro,Stylized,3D,Casual,Controller,Sci-fi,Indie                    14.0
1980s,Old School,PvP,Local Multiplayer,Multiplayer,Retro,Strategy,Space,Arcade,Minimalist,Pixel Graphics,Action,2D,Top-Down,Bullet Hell,Fighting,Top-Down Shooter,Competitive,Free to Play                        22.0
1980s,Platformer,Side Scroller,Pixel Graphics,Retro,Difficult,2D Platformer,Action,Old School,Metroidvania,Indie,2D,Singleplayer,Arcade,Destruction,Rock Music,Spectacle fighter,Soundtrack,Atmospheric,Comedy     6.0
Name: Positive, dtype: float64

In [8]:
new_tags_review_df = game_df['Tags'].str.split(",").str.join('|').str.get_dummies()
new_tags_review_df

,1980s,1990's,2.5D,2D,2D Fighter,2D Platformer,360 Video,3D,3D Fighter,3D Platformer,...,Well-Written,Werewolves,Western,Wholesome,Word Game,World War I,World War II,Wrestling,Zombies,e-sports
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74686,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
74688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
tags_sum_df = new_tags_review_df.sum()
tags_sum_df = tags_sum_df.sort_values(ascending=False)
tags_sum_df = tags_sum_df.head(20)
tags_sum_df

Indie             37644
Singleplayer      29642
Action            26487
Casual            25345
Adventure         24668
2D                15714
Strategy          12502
Simulation        12297
RPG               10916
Puzzle            10447
Atmospheric       10111
3D                 8447
Early Access       8327
Pixel Graphics     8205
Story Rich         8086
Colorful           7752
Multiplayer        7187
Cute               7131
Arcade             7004
Exploration        6823
dtype: int64

In [24]:
owners_df = game_df[["Name", "Estimated owners"]]
owners_df = owners_df.head(20)
owners_df

                                  Name Estimated owners
0                     Galactic Bowling        0 - 20000
1                         Train Bandit        0 - 20000
2                         Jolt Project        0 - 20000
3                             Henosis™        0 - 20000
4                Two Weeks in Painland        0 - 20000
5                       Wartune Reborn   50000 - 100000
6                            TD Worlds        0 - 20000
7   Legend of Rome - The Wrath of Mars        0 - 20000
8                MazM: Jekyll and Hyde        0 - 20000
9            Deadlings: Rotten Edition   50000 - 100000
10                              WARSAW    20000 - 50000
11                      Cthulhu Realms   50000 - 100000
12                   Clockwork Dungeon        0 - 20000
13                   Royal Battleships    20000 - 50000
14                      Diary of Lucie        0 - 20000
15              Alien Breed 3: Descent  200000 - 500000
16                 Hunting Unlimited 3        0 - 20000
17              Hero of the Kingdom II  100000 - 200000
18                Super Naughty Maid 2        0 - 20000
19                                KHIO        0 - 20000

In [38]:
owners_df = game_df[["Name", "Estimated owners"]]
owners_df = owners_df.sort_values("Estimated owners", ascending=False)
owners_df.head(20)

                                              Name      Estimated owners
7030                                     New World  50000000 - 100000000
46158             Counter-Strike: Global Offensive  50000000 - 100000000
30583                              Team Fortress 2  50000000 - 100000000
8885                           PUBG: BATTLEGROUNDS  50000000 - 100000000
43468                        Red Dead Redemption 2    5000000 - 10000000
5806                        A Story About My Uncle    5000000 - 10000000
38736                              Fallout Shelter    5000000 - 10000000
37677             Middle-earth™: Shadow of Mordor™    5000000 - 10000000
6262                      Age of Empires II (2013)    5000000 - 10000000
69429                              Hogwarts Legacy    5000000 - 10000000
29925                 Counter-Strike Nexon: Studio    5000000 - 10000000
50309                                Hollow Knight    5000000 - 10000000
48127  The Elder Scrolls V: Skyrim Special Edition    5000000 - 10000000
7076                                Evolve Stage 2    5000000 - 10000000
59333                                      XCOM® 2    5000000 - 10000000
7062                              Castle Crashers®    5000000 - 10000000
2758                      Half-Life 2: Episode Two    5000000 - 10000000
34805                                    Fallout 4    5000000 - 10000000
49557                                    Half-Life    5000000 - 10000000
61511                                       Deceit    5000000 - 10000000

In [ ]:
#find estimated owners for genres
#find estimated owners for tags
#find estimated owners for developers
#find estimated owners for publishers

In [15]:
genres_df = game_df[["Genres","Estimated owners"]]
genres_df = genres_df.sort_values("Estimated owners", ascending=False)
genres_df.head(20)

                                                  Genres      Estimated owners
7030          Action,Adventure,Massively Multiplayer,RPG  50000000 - 100000000
46158                                Action,Free to Play  50000000 - 100000000
30583                                Action,Free to Play  50000000 - 100000000
8885   Action,Adventure,Free to Play,Massively Multip...  50000000 - 100000000
43468                                   Action,Adventure    5000000 - 10000000
5806                              Adventure,Casual,Indie    5000000 - 10000000
38736                        Free to Play,RPG,Simulation    5000000 - 10000000
37677                                                NaN    5000000 - 10000000
6262                                            Strategy    5000000 - 10000000
69429                               Action,Adventure,RPG    5000000 - 10000000
29925   Action,Casual,Free to Play,Massively Multiplayer    5000000 - 10000000
50309                             Action,Adventure,Indie    5000000 - 10000000
48127                                                RPG    5000000 - 10000000
7076                                 Action,Free to Play    5000000 - 10000000
59333                                           Strategy    5000000 - 10000000
7062                   Action,Adventure,Casual,Indie,RPG    5000000 - 10000000
2758                                              Action    5000000 - 10000000
34805                                                RPG    5000000 - 10000000
49557                                             Action    5000000 - 10000000
61511                          Action,Free to Play,Indie    5000000 - 10000000

In [16]:
tag_df = game_df[["Tags","Estimated owners"]]
tag_df = tag_df.sort_values("Estimated owners", ascending=False)
tag_df.head(20)

                                                    Tags      Estimated owners
7030   Massively Multiplayer,Open World,MMORPG,RPG,Ad...  50000000 - 100000000
46158  FPS,Shooter,Multiplayer,Competitive,Action,Tea...  50000000 - 100000000
30583  Free to Play,Hero Shooter,Multiplayer,FPS,Shoo...  50000000 - 100000000
8885   Survival,Shooter,Multiplayer,Battle Royale,FPS...  50000000 - 100000000
43468  Open World,Adventure,Story Rich,Western,Action...    5000000 - 10000000
5806   Adventure,First-Person,Parkour,Singleplayer,In...    5000000 - 10000000
38736  Free to Play,Base-Building,Survival,Post-apoca...    5000000 - 10000000
37677  Open World,Action,Fantasy,Adventure,Third Pers...    5000000 - 10000000
6262   Strategy,RTS,Medieval,Multiplayer,Classic,Hist...    5000000 - 10000000
69429  Magic,Fantasy,Open World,Adventure,Singleplaye...    5000000 - 10000000
29925  Free to Play,Zombies,Multiplayer,Sandbox,FPS,S...    5000000 - 10000000
50309  Metroidvania,Souls-like,Platformer,Great Sound...    5000000 - 10000000
48127  Open World,RPG,Adventure,Singleplayer,Fantasy,...    5000000 - 10000000
7076   Action,Multiplayer,Co-op,FPS,Online Co-Op,Shoo...    5000000 - 10000000
59333  Strategy,Turn-Based,Turn-Based Strategy,Tactic...    5000000 - 10000000
7062   Co-op,Action,Multiplayer,Adventure,Local Co-Op...    5000000 - 10000000
2758   FPS,Action,Sci-fi,Singleplayer,Shooter,Story R...    5000000 - 10000000
34805  Open World,Post-apocalyptic,Exploration,Single...    5000000 - 10000000
49557  FPS,Singleplayer,Sci-fi,Multiplayer,1990's,Act...    5000000 - 10000000
61511  PvP,Free to Play,Multiplayer,Horror,Social Ded...    5000000 - 10000000

In [40]:
developer_df = game_df[["Developers","Estimated owners"]]
developer_df = developer_df.sort_values("Estimated owners", ascending=False)
developer_df.head(20)

                                              Developers      Estimated owners
7030                                        Amazon Games  50000000 - 100000000
46158                    Valve,Hidden Path Entertainment  50000000 - 100000000
30583                                              Valve  50000000 - 100000000
8885                                       KRAFTON, Inc.  50000000 - 100000000
43468                                     Rockstar Games    5000000 - 10000000
5806                                    Gone North Games    5000000 - 10000000
38736                              Bethesda Game Studios    5000000 - 10000000
37677                               Monolith Productions    5000000 - 10000000
6262   Skybox Labs,Hidden Path Entertainment,Ensemble...    5000000 - 10000000
69429                                 Avalanche Software    5000000 - 10000000
29925         Valve Corporation, Nexon Korea Corporation    5000000 - 10000000
50309                                        Team Cherry    5000000 - 10000000
48127                              Bethesda Game Studios    5000000 - 10000000
7076                                 Turtle Rock Studios    5000000 - 10000000
59333  Firaxis Games,Feral Interactive (Mac),Feral In...    5000000 - 10000000
7062                                        The Behemoth    5000000 - 10000000
2758                                               Valve    5000000 - 10000000
34805                              Bethesda Game Studios    5000000 - 10000000
49557                                              Valve    5000000 - 10000000
61511                                       World Makers    5000000 - 10000000

In [18]:
publisher_df = game_df[["Publishers","Estimated owners"]]
publisher_df = publisher_df.sort_values("Estimated owners", ascending=False)
publisher_df.head(20)

                                              Publishers      Estimated owners
7030                                        Amazon Games  50000000 - 100000000
46158                                              Valve  50000000 - 100000000
30583                                              Valve  50000000 - 100000000
8885                                       KRAFTON, Inc.  50000000 - 100000000
43468                                     Rockstar Games    5000000 - 10000000
5806                             Coffee Stain Publishing    5000000 - 10000000
38736                                 Bethesda Softworks    5000000 - 10000000
37677  Warner Bros. Interactive Entertainment,Warner ...    5000000 - 10000000
6262                                   Xbox Game Studios    5000000 - 10000000
69429                                 Warner Bros. Games    5000000 - 10000000
29925                            Nexon Korea Corporation    5000000 - 10000000
50309                                        Team Cherry    5000000 - 10000000
48127                                 Bethesda Softworks    5000000 - 10000000
7076                                                  2K    5000000 - 10000000
59333  2K,Feral Interactive (Mac),Feral Interactive (...    5000000 - 10000000
7062                                        The Behemoth    5000000 - 10000000
2758                                               Valve    5000000 - 10000000
34805                                 Bethesda Softworks    5000000 - 10000000
49557                                              Valve    5000000 - 10000000
61511                                       World Makers    5000000 - 10000000